### ISSUE TITLE
px-dark-theme does not work with predix-seed-app

### ISSUE THREAD

**Issue by patrick-bergeron** [PredixDev/px-dark-theme#3]
Replace

`<link rel="import" href="seed-app-styles.html">`

with

`<link rel="import" href="/bower_components/px-dark-theme/px-dark-theme-styles.html"/>`

and

`<style include="seed-app-styles"></style>`

with

`<style include="px-dark-theme-styles"></style>`

The app does not render correctly.

**Comment by randyaskin** [comment]
Seed-app-styles is different than px-theme/px-dark-theme. If you want to use the dark-theme, you should update these two lines of code: https://github.com/PredixDev/predix-seed/blob/master/public/_index.html#L15-L16
